/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PrintingHistoryLazyImport = createFileRoute('/printing-history')()
const PrivatePrintPrintLazyImport = createFileRoute('/_private/_print/print')()
const PrivatePrintConfigPageLazyImport = createFileRoute(
  '/_private/_print/config-page',
)()
const PrivatePrintChoosePrinterLazyImport = createFileRoute(
  '/_private/_print/choose-printer',
)()

// Create/Update Routes

const PrintingHistoryLazyRoute = PrintingHistoryLazyImport.update({
  id: '/printing-history',
  path: '/printing-history',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/printing-history.lazy').then((d) => d.Route),
)

const PrivatePrintPrintLazyRoute = PrivatePrintPrintLazyImport.update({
  id: '/_private/_print/print',
  path: '/print',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_private/_print/print.lazy').then((d) => d.Route),
)

const PrivatePrintConfigPageLazyRoute = PrivatePrintConfigPageLazyImport.update(
  {
    id: '/_private/_print/config-page',
    path: '/config-page',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/_private/_print/config-page.lazy').then((d) => d.Route),
)

const PrivatePrintChoosePrinterLazyRoute =
  PrivatePrintChoosePrinterLazyImport.update({
    id: '/_private/_print/choose-printer',
    path: '/choose-printer',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/_private/_print/choose-printer.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/printing-history': {
      id: '/printing-history'
      path: '/printing-history'
      fullPath: '/printing-history'
      preLoaderRoute: typeof PrintingHistoryLazyImport
      parentRoute: typeof rootRoute
    }
    '/_private/_print/choose-printer': {
      id: '/_private/_print/choose-printer'
      path: '/choose-printer'
      fullPath: '/choose-printer'
      preLoaderRoute: typeof PrivatePrintChoosePrinterLazyImport
      parentRoute: typeof rootRoute
    }
    '/_private/_print/config-page': {
      id: '/_private/_print/config-page'
      path: '/config-page'
      fullPath: '/config-page'
      preLoaderRoute: typeof PrivatePrintConfigPageLazyImport
      parentRoute: typeof rootRoute
    }
    '/_private/_print/print': {
      id: '/_private/_print/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrivatePrintPrintLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/printing-history': typeof PrintingHistoryLazyRoute
  '/choose-printer': typeof PrivatePrintChoosePrinterLazyRoute
  '/config-page': typeof PrivatePrintConfigPageLazyRoute
  '/print': typeof PrivatePrintPrintLazyRoute
}

export interface FileRoutesByTo {
  '/printing-history': typeof PrintingHistoryLazyRoute
  '/choose-printer': typeof PrivatePrintChoosePrinterLazyRoute
  '/config-page': typeof PrivatePrintConfigPageLazyRoute
  '/print': typeof PrivatePrintPrintLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/printing-history': typeof PrintingHistoryLazyRoute
  '/_private/_print/choose-printer': typeof PrivatePrintChoosePrinterLazyRoute
  '/_private/_print/config-page': typeof PrivatePrintConfigPageLazyRoute
  '/_private/_print/print': typeof PrivatePrintPrintLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/printing-history' | '/choose-printer' | '/config-page' | '/print'
  fileRoutesByTo: FileRoutesByTo
  to: '/printing-history' | '/choose-printer' | '/config-page' | '/print'
  id:
    | '__root__'
    | '/printing-history'
    | '/_private/_print/choose-printer'
    | '/_private/_print/config-page'
    | '/_private/_print/print'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrintingHistoryLazyRoute: typeof PrintingHistoryLazyRoute
  PrivatePrintChoosePrinterLazyRoute: typeof PrivatePrintChoosePrinterLazyRoute
  PrivatePrintConfigPageLazyRoute: typeof PrivatePrintConfigPageLazyRoute
  PrivatePrintPrintLazyRoute: typeof PrivatePrintPrintLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  PrintingHistoryLazyRoute: PrintingHistoryLazyRoute,
  PrivatePrintChoosePrinterLazyRoute: PrivatePrintChoosePrinterLazyRoute,
  PrivatePrintConfigPageLazyRoute: PrivatePrintConfigPageLazyRoute,
  PrivatePrintPrintLazyRoute: PrivatePrintPrintLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/printing-history",
        "/_private/_print/choose-printer",
        "/_private/_print/config-page",
        "/_private/_print/print"
      ]
    },
    "/printing-history": {
      "filePath": "printing-history.lazy.tsx"
    },
    "/_private/_print/choose-printer": {
      "filePath": "_private/_print/choose-printer.lazy.tsx"
    },
    "/_private/_print/config-page": {
      "filePath": "_private/_print/config-page.lazy.tsx"
    },
    "/_private/_print/print": {
      "filePath": "_private/_print/print.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
