/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PrintingHistoryLazyImport = createFileRoute('/printing-history')()
const PrintBuyLazyImport = createFileRoute('/print/buy')()
const ManageReportLazyImport = createFileRoute('/manage/report')()

// Create/Update Routes

const PrintingHistoryLazyRoute = PrintingHistoryLazyImport.update({
  id: '/printing-history',
  path: '/printing-history',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/printing-history.lazy').then((d) => d.Route),
)

const PrintBuyLazyRoute = PrintBuyLazyImport.update({
  id: '/print/buy',
  path: '/print/buy',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/print/buy.lazy').then((d) => d.Route))

const ManageReportLazyRoute = ManageReportLazyImport.update({
  id: '/manage/report',
  path: '/manage/report',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/manage/report.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/printing-history': {
      id: '/printing-history'
      path: '/printing-history'
      fullPath: '/printing-history'
      preLoaderRoute: typeof PrintingHistoryLazyImport
      parentRoute: typeof rootRoute
    }
    '/manage/report': {
      id: '/manage/report'
      path: '/manage/report'
      fullPath: '/manage/report'
      preLoaderRoute: typeof ManageReportLazyImport
      parentRoute: typeof rootRoute
    }
    '/print/buy': {
      id: '/print/buy'
      path: '/print/buy'
      fullPath: '/print/buy'
      preLoaderRoute: typeof PrintBuyLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/printing-history': typeof PrintingHistoryLazyRoute
  '/manage/report': typeof ManageReportLazyRoute
  '/print/buy': typeof PrintBuyLazyRoute
}

export interface FileRoutesByTo {
  '/printing-history': typeof PrintingHistoryLazyRoute
  '/manage/report': typeof ManageReportLazyRoute
  '/print/buy': typeof PrintBuyLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/printing-history': typeof PrintingHistoryLazyRoute
  '/manage/report': typeof ManageReportLazyRoute
  '/print/buy': typeof PrintBuyLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/printing-history' | '/manage/report' | '/print/buy'
  fileRoutesByTo: FileRoutesByTo
  to: '/printing-history' | '/manage/report' | '/print/buy'
  id: '__root__' | '/printing-history' | '/manage/report' | '/print/buy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  PrintingHistoryLazyRoute: typeof PrintingHistoryLazyRoute
  ManageReportLazyRoute: typeof ManageReportLazyRoute
  PrintBuyLazyRoute: typeof PrintBuyLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  PrintingHistoryLazyRoute: PrintingHistoryLazyRoute,
  ManageReportLazyRoute: ManageReportLazyRoute,
  PrintBuyLazyRoute: PrintBuyLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/printing-history",
        "/manage/report",
        "/print/buy"
      ]
    },
    "/printing-history": {
      "filePath": "printing-history.lazy.tsx"
    },
    "/manage/report": {
      "filePath": "manage/report.lazy.tsx"
    },
    "/print/buy": {
      "filePath": "print/buy.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
